package org.example.steps;

import com.codeborne.selenide.CollectionCondition;
import com.codeborne.selenide.SelenideElement;
import org.example.models.BreadCrumbs;
import org.example.models.ProductData;
import org.example.pages.CartPage;
import org.example.pages.DirectCategoryPage;
import org.example.pages.MainPage;
import org.example.pages.PopUpPages;
import org.example.utils.ClosePopUp;
import org.example.utils.Waiters;

import java.util.Arrays;

import static com.codeborne.selenide.Condition.text;

public class MainMenuSteps {

    MainPage mainPage = new MainPage();

    public void clickMainMenu(String headerMenu) {
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
//        Waiters.sleep();
        System.out.println(mainPage.headerMenuButtons(headerMenu) + " --- clickMainMenu");
        mainPage.headerMenuButtons(headerMenu).hover().click();
    }

    public String getBreadCrumb(String breadCrumb) {
//        BreadCrumbs breadCrumb = new BreadCrumbs();
        System.out.println(mainPage.breadCrumbName(breadCrumb).getText() + " --- SeeBreadCrumb");
        mainPage.breadCrumbName(breadCrumb).getText();
        return breadCrumb;
    }
//    public BreadCrumbs getBreadCrumb() {
//        BreadCrumbs breadCrumb = new BreadCrumbs();
//        System.out.println(" --- SeeBreadCrumb");
//        breadCrumb.setBreadCrumb(mainPage.breadCrumbName(breadCrumb.getBreadCrumb()).getText());
//        return breadCrumb;
//    }
}
